# Generated by Django 5.2.5 on 2025-09-10 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook_app', '0003_userprofile_role_alter_userprofile_gender_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
